# Configuración del PluginLoader & Downloader

# Configuración para descargar artefactos de GitHub
github:
  enabled: true
  check-interval: 60 #Intervalo de comprobación de actualizaciones en minutos (predeterminado: 60)
  delete-after-extract: true # Eliminar archivos ZIP después de extraer los plugins
  check-on-startup: true # Comprobar automáticamente actualizaciones al iniciar
  auto-update-on-startup: true # Actualizar automáticamente en startup
  # Lista de repositorios para descargar artefactos
  repositories:
    example-plugin:
      owner: "example-user"         # Usuario o organización de GitHub
      repo: "example-repo"      # Nombre del repositorio
      workflow: "build.yml"       # Nombre del archivo de workflow
      branch: "master"              # Rama para buscar ejecuciones
      artifact: "Plugin*"    # Patrón para el nombre del artefacto
      token: ""                   # Token de GitHub (opcional, para repos privados)
      auto-update: true           # Además de descargar si no está instalado ya, Actualizar automáticamente este plugin

    # Puedes agregar más repositorios si es necesario
    # otro-plugin:
    #   owner: "otro-usuario"
    #   repo: "otro-repo"
    #   workflow: "maven.yml"
    #   branch: "master"
    #   artifact: "Plugin2*"
    #   auto-update: false        # Este plugin no se actualizará automáticamente