name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -T4
    - name: Start obfuscation
      run: |
        java -jar obf.jar target/PluginLoader.jar out
        cd out/cpp
        cmake .
        cmake --build . --config
    - name: Uploading File
      uses: actions/upload-artifact@v4
      with:
        name: "PluginLoader"
        path: target/PluginLoader*.jar
