name: Java CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -T4
    - name: Start obfuscation
      run: |
        java -jar obf.jar target/PluginLoader-git*.jar out
    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: out/cpp/
        build-dir: out/build/
    - name: After build processing
      run: |
        ls out/build/build/lib
        mkdir out/zippin
        mv out/PluginLoader-git*.jar out/zippin
        cd out/zippin
        unzip PluginLoader-git*.jar
        rm PluginLoader-git*.jar
        mv ../build/build/lib/libnative_library.so native0/x64-linux.so
        zip -r ../PluginLoader-final.jar .
        cd ../../
    - name: Uploading File
      uses: actions/upload-artifact@v4
      with:
        name: "PluginLoader"
        path: out/PluginLoader-final.jar
